FestinaLenteApp/src/objects/AvailableDate__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Available Dates</relationshipLabel>
        <relationshipName>AvailableDates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <formula>CASE(DayOfWeekNumber__c, 
    0, &apos;Sunday&apos;, 
    1, &apos;Monday&apos;, 
    2, &apos;Tuesday&apos;, 
    3, &apos;Wednesday&apos;, 
    4, &apos;Thursday&apos;, 
    5, &apos;Friday&apos;, 
    6, &apos;Saturday&apos;, 
    &apos;&apos;
)</formula>
        <label>Day of Week</label>
        <type>Text</type>
    </fields>
    <label>Available Date</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Available Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AvailableDates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/BookedDate__c.object
<CustomObject>
    <fields>
        <fullName>AvailableDate__c</fullName>
        <label>Available Date</label>
        <referenceTo>AvailableDate__c</referenceTo>
        <relationshipLabel>Booked Dates</relationshipLabel>
        <relationshipName>BookedDates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Booked Dates</relationshipLabel>
        <relationshipName>BookedDates</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <formula>HYPERLINK( Booking__r.Client__r.Id ,  Booking__r.Client__r.FirstName + &apos; &apos; +  Booking__r.Client__r.LastName , &quot;_self&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <formula>AvailableDate__r.Date__c</formula>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <formula>AvailableDate__r.DayOfWeek__c</formula>
        <label>Day of Week</label>
        <type>Text</type>
    </fields>
    <label>Booked Date</label>
    <nameField>
        <displayFormat>BD-{000000}</displayFormat>
        <label>Booked Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booked Dates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Booking__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Class__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Coach__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Coach</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <label>Day of Week</label>
        <picklist>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PreferredHorse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred Horse</label>
        <referenceTo>Horse__c</referenceTo>
        <relationshipLabel>Preferring Clients</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <label>Client</label>
    </recordTypes>
    <recordTypes>
        <fullName>Coach</fullName>
        <active>true</active>
        <label>Coach</label>
    </recordTypes>
</CustomObject>

FestinaLenteApp/src/objects/Horse__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <label>Horse</label>
    <nameField>
        <label>Horse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Horses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FestinaLenteApp/src/classes/CalendarControllerTest.cls
@isTest
private class CalendarControllerTest {

    private class Fixture {
    
        Horse__c horse;
        Contact coach;
        Class__c clazz;
        Contact client;
        Booking__c booking;
        AvailableDate__c ad1;
        BookedDate__c bd1;
        AvailableDate__c ad2;
        
        Fixture() {
        
            horse = new Horse__c(Name = 'Paddy');
            insert horse;
            
            coach = new Contact(
                    FirstName = 'Jane',
                    LastName = 'Coach',
                    RecordTypeId = [
                            select Id
                            from RecordType
                            where DeveloperName = 'Coach'
                            and SObjectType = :String.valueOf(Contact.SObjectType)
                            ].Id
                    );
            insert coach;
            
            clazz = new Class__c(Coach__c = coach.Id, DayOfWeek__c = 'Monday');
            insert clazz;
            
            client = new Contact(
                    FirstName = 'John',
                    LastName = 'Client',
                    PreferredHorse__c = horse.Id,
                    RecordTypeId = [
                            select Id
                            from RecordType
                            where DeveloperName = 'Client'
                            and SObjectType = :String.valueOf(Contact.SObjectType)
                            ].Id
                    );
            insert client;
            
            booking = new Booking__c(Class__c = clazz.Id, Client__c = client.Id);
            insert booking;
            
            ad1 = new AvailableDate__c(Class__c = clazz.Id, Date__c = Date.newInstance(2013, 2, 18));
            insert ad1;
            
            ad2 = new AvailableDate__c(Class__c = clazz.Id, Date__c = Date.newInstance(2013, 2, 25));
            insert ad2;
            
            bd1 = new BookedDate__c(AvailableDate__c = ad1.Id, Booking__c = booking.Id);
            insert bd1;
        }
        
        void addIdsToCurrentPage() {

            Map<String, String> p = ApexPages.currentPage().getParameters();
            p.put('clientId', client.Id);
            p.put('coachId', coach.Id);
            p.put('horseId', horse.Id);
            p.put('bookingId', booking.Id);
            p.put('classId', clazz.Id);
        }
    }

    @isTest
    static void events() {
    
        Fixture f = new Fixture();

        // No ids in URL
        CalendarController c1 = new CalendarController();
        c1.init();
        System.assertNotEquals(null, c1.events);
        
        // All ids in URL
        f.addIdsToCurrentPage();
        CalendarController c2 = new CalendarController();
        c2.init();
        System.assertNotEquals(null, c2.events);
    }
}