FestinaLenteApp/src/objects/AvailableDate__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Available Dates</relationshipLabel>
        <relationshipName>AvailableDates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <formula>CASE(DayOfWeekNumber__c, 
    0, &apos;Sunday&apos;, 
    1, &apos;Monday&apos;, 
    2, &apos;Tuesday&apos;, 
    3, &apos;Wednesday&apos;, 
    4, &apos;Thursday&apos;, 
    5, &apos;Friday&apos;, 
    6, &apos;Saturday&apos;, 
    &apos;&apos;
)</formula>
        <label>Day of Week</label>
        <type>Text</type>
    </fields>
    <label>Available Date</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Available Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AvailableDates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Class__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <label>Day of Week</label>
        <picklist>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FestinaLenteApp/src/classes/ClassAfterTest.cls
@isTest
private class ClassAfterTest {

    private class Fixture {
    
        Class__c clazz;
        AvailableDate__c ad;

        Fixture() {
            
            clazz = new Class__c(DayOfWeek__c = 'Monday');
            insert clazz;
            
            // Monday
            ad = new AvailableDate__c(Class__c = clazz.Id, Date__c = Date.newInstance(2013, 2, 18));
            insert ad;
        }
    }
    
    @isTest
    static void changeDayOfWeek() {
    
        Fixture f = new Fixture();
        f.clazz.DayOfWeek__c = 'Thursday';
        update f.clazz;
        
        System.assertEquals('Thursday', [select DayOfWeek__c from AvailableDate__c where Id =:f.ad.Id].DayOfWeek__c);
    }
}