FestinaLenteApp/src/objects/AvailableDate__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Available Dates</relationshipLabel>
        <relationshipName>AvailableDates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Available Date</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Available Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AvailableDates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/BookedDate__c.object
<CustomObject>
    <fields>
        <fullName>AvailableDate__c</fullName>
        <label>Available Date</label>
        <referenceTo>AvailableDate__c</referenceTo>
        <relationshipLabel>Booked Dates</relationshipLabel>
        <relationshipName>BookedDates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Booked Dates</relationshipLabel>
        <relationshipName>BookedDates</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <formula>HYPERLINK( Booking__r.Client__r.Id ,  Booking__r.Client__r.FirstName + &apos; &apos; +  Booking__r.Client__r.LastName , &quot;_self&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <formula>AvailableDate__r.Date__c</formula>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Booked Date</label>
    <nameField>
        <displayFormat>BD-{000000}</displayFormat>
        <label>Booked Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booked Dates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Booking__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EarliestBookedDate__c</fullName>
        <label>Earliest Booked Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LatestBookedDate__c</fullName>
        <label>Latest Booked Date</label>
        <type>Date</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Class__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Coach__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Coach</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Detail__c</fullName>
        <label>Detail</label>
        <picklist>
            <picklistValues>
                <fullName>Lesson</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Stable Management then Lesson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lesson then Stable Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LengthInMinutes__c</fullName>
        <formula>CASE( Length__c,
    &apos;Day&apos;, 480,
    &apos;Half Day&apos;, 240,
    &apos;90 mins&apos;, 90,
    &apos;60 mins&apos;, 60,
    &apos;45 mins&apos;, 45,
    &apos;30 mins&apos;, 30,
    &apos;2 hours&apos;, 120,
    &apos;2 hours 30 mins&apos;, 150,
    &apos;3 hours&apos;, 180,
    &apos;3 hours 30 mins&apos;, 210,
    &apos;4 hours&apos;, 240,
    &apos;4 hours 30 mins&apos;, 270,
    &apos;5 hours&apos;, 300,
    &apos;5 hours 30 mins&apos;, 330,
    &apos;6 hours&apos;, 360,
    &apos;6 hours 30 mins&apos;, 390,
    &apos;7 hours&apos;, 420,
    &apos;7 hours 30 mins&apos;, 450,
    NULL
)</formula>
        <label>Length in Minutes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>B - Beginner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI - Beginner Improver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I - Intermediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SI - Strong Intermediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A - Advanced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TimeInMinutes__c</fullName>
        <formula>CASE(Time__c,
&apos;8 am&apos;, 480,
&apos;8:15 am&apos;, 495,
&apos;8:30 am&apos;, 510,
&apos;8:45 am&apos;, 525,
&apos;9 am&apos;, 540,
&apos;9:15 am&apos;, 555,
&apos;9:30 am&apos;, 570,
&apos;9:45 am&apos;, 585,
&apos;10 am&apos;, 600,
&apos;10:15 am&apos;, 615,
&apos;10:30 am&apos;, 630,
&apos;10:45 am&apos;, 645,
&apos;11 am&apos;, 660,
&apos;11:15 am&apos;, 675,
&apos;11:30 am&apos;, 690,
&apos;11:45 am&apos;, 705,
&apos;12 pm&apos;, 720,
&apos;12:15 pm&apos;, 735,
&apos;12:30 pm&apos;, 750,
&apos;12:45 pm&apos;, 765,
&apos;1 pm&apos;, 780,
&apos;1:15 pm&apos;, 795,
&apos;1:30 pm&apos;, 810,
&apos;1:45 pm&apos;, 825,
&apos;2 pm&apos;, 840,
&apos;2:15 pm&apos;, 855,
&apos;2:30 pm&apos;, 870,
&apos;2:45 pm&apos;, 885,
&apos;3 pm&apos;, 900,
&apos;3:15 pm&apos;, 915,
&apos;3:30 pm&apos;, 930,
&apos;3:45 pm&apos;, 945,
&apos;4 pm&apos;, 960,
&apos;4:15 pm&apos;, 975,
&apos;4:30 pm&apos;, 990,
&apos;4:45 pm&apos;, 1005,
&apos;5 pm&apos;, 1020,
&apos;5:15 pm&apos;, 1035,
&apos;5:30 pm&apos;, 1050,
&apos;5:45 pm&apos;, 1065,
&apos;6 pm&apos;, 1080,
&apos;6:15 pm&apos;, 1095,
&apos;6:30 pm&apos;, 1110,
&apos;6:45 pm&apos;, 1125,
null
)</formula>
        <label>Time in Minutes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Adult Camp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EAL Session</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Educational Helpers Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFEP Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pony Camp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Lesson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Private Lesson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Needs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stable Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supported Helpers Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Therapeutic Lesson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training: EAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training: TCP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>B - Beginner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI - Beginner Improver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I - Intermediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SI - Strong Intermediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A - Advanced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PreferredHorse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred Horse</label>
        <referenceTo>Horse__c</referenceTo>
        <relationshipLabel>Preferring Clients</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <label>Client</label>
    </recordTypes>
    <recordTypes>
        <fullName>Coach</fullName>
        <active>true</active>
        <label>Coach</label>
    </recordTypes>
</CustomObject>

FestinaLenteApp/src/objects/Filter__c.object
<CustomObject>
    <description>Object ids used for filtering. Not persisted.</description>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Filters</relationshipLabel>
        <relationshipName>Filters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Filters</relationshipLabel>
        <relationshipName>Filters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Filters</relationshipLabel>
        <relationshipName>ClientFilters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Coach__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Coach</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Filters (Coach)</relationshipLabel>
        <relationshipName>CoachFilters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Horse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Horse</label>
        <referenceTo>Horse__c</referenceTo>
        <relationshipLabel>Filters</relationshipLabel>
        <relationshipName>Filters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShowAvailable__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShowBooked__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show Booked</label>
        <type>Checkbox</type>
    </fields>
    <label>Filter</label>
    <nameField>
        <label>Filter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Horse__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <label>Horse</label>
    <nameField>
        <label>Horse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Horses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FestinaLenteApp/src/classes/CalendarController.cls
public with sharing class CalendarController {

    private static final String W = ' where ';
    private static final String A = ' and ';

    public Filter__c filter {get; private set;}
    public List<Back> backs {get; private set;}

    // Used for breadcrumbs
    public class Back {
        public Id id {get; private set;}
        public String name {get; private set;}
        public Back(Id id, String name) {
            this.id = id;
            this.name = name;
        }
    }

    public PageReference init() {

        Map<String, String> p = ApexPages.currentPage().getParameters();
        
        String clientId = p.get('clientId');
        String coachId = p.get('coachId');
        String horseId = p.get('horseId');
        String bookingId = p.get('bookingId');
        String classId = p.get('classId');
        
        // Transfer to fields for display/editing
        filter = new Filter__c(ShowBooked__c = true, ShowAvailable__c = true);
        if (clientId != null) {
            filter.Client__c = clientId;
        }
        if (coachId != null) {
            filter.Coach__c = coachId;
        }
        if (horseId != null) {
            filter.Horse__c = horseId;
        }
        if (bookingId != null) {
            filter.Booking__c = bookingId;
        }
        if (classId != null) {
            filter.Class__c = classId;
        }
        
        backs = new List<Back>();

        // Order here should match order of filter fields in page so "back" links are in matching order
        if (clientId != null) {
            backs.add(new Back(clientId, [select Name from Contact where Id = :clientId].Name));
        }
        if (coachId != null) {
            backs.add(new Back(coachId, [select Name from Contact where Id = :coachId].Name));
        }
        if (horseId != null) {
            backs.add(new Back(horseId, [select Name from Horse__c where Id = :horseId].Name));
        }
        if (bookingId != null) {
            backs.add(new Back(bookingId, [select Name from Booking__c where Id = :bookingId].Name));
        }
        if (classId != null) {
            backs.add(new Back(classId, [select Name from Class__c where Id = :classId].Name));
        }
        
        return null;
    }
  
    public PageReference refresh() {
    
        // Detailed data is transient so this will cause a re-generation using the current filter
        return null;
    }
    
    private BookedDate__c[] queryBookedDates() {
    
        // Only simple variables can be bound into queries
        String clientId = filter.Client__c;
        String coachId = filter.Coach__c;
        String horseId = filter.Horse__c;
        String bookingId = filter.Booking__c;
        String classId = filter.Class__c;
        
        // Build query
        String soql = ''
                + ' select'
                + '         Id, Name, Date__c,'
                + '         AvailableDate__r.Id,'
                + '         Booking__r.Id, Booking__r.Name, Booking__r.EarliestBookedDate__c, Booking__r.LatestBookedDate__c,'
                + '         Booking__r.Client__r.Name, Booking__r.Client__r.Level__c,'
                + '         Booking__r.Client__r.PreferredHorse__r.Name,'
                + '         Booking__r.Class__r.Coach__r.Name,'
                + '         Booking__r.Class__r.Id, Booking__r.Class__r.Name, Booking__r.Class__r.TimeInMinutes__c, Booking__r.Class__r.LengthInMinutes__c,'
                + '         Booking__r.Class__r.Type__c, Booking__r.Class__r.Detail__c, Booking__r.Class__r.Level__c'
                + ' from BookedDate__c'
                ;
        String op = W;
        if (clientId != null) {
            soql += op + 'Booking__r.Client__r.Id = :clientId';
            op = A;
        }
        if (coachId != null) {
            soql += op + 'Booking__r.Class__r.Coach__r.Id = :coachId';
            op = A;
        }
        if (horseId != null) {
            soql += op + 'Booking__r.Client__r.PreferredHorse__r.Id = :horseId';
            op = A;
        }
        if (bookingId != null) {
            soql += op + 'Booking__r.Id = :bookingId';
            op = A;
        }
        if (classId != null) {
            soql += op + 'Booking__r.Class__r.Id = :classId';
            op = A;
        }
        
        System.debug('>>> booked dates soql=' + soql);
        return Database.query(soql);
    }
    
    private AvailableDate__c[] queryAvailableDates(Set<Id> skipIds) {
    
        // Only simple variables can be bound into queries
        String coachId = filter.Coach__c;
        String classId = filter.Class__c;
        
        // Build query
        String soql = ''
                + ' select'
                + '         Id, Name, Date__c,'
                + '         Class__r.Coach__r.Name,'
                + '         Class__r.Id, Class__r.Name, Class__r.TimeInMinutes__c, Class__r.LengthInMinutes__c,'
                + '         Class__r.Type__c, Class__r.Detail__c, Class__r.Level__c'
                + ' from AvailableDate__c'
                ;
        String op = W;
        if (coachId != null) {
            soql += op + 'Class__r.Coach__r.Id = :coachId';
            op = A;
        }
        if (classId != null) {
            soql += op + 'Class__r.Id = :classID';
            op = A;
        }
        
        // If already being presented as a booked date don't show again as an available date
        if (skipIds.size() > 0) {
            soql += op + 'Id not in :skipIds';
            op = A;
        }
        
        System.debug('>>> available dates soql=' + soql);
        return Database.query(soql);
    }

    public String events {
        get {
            JSONGenerator g = JSON.createGenerator(true);
            g.writeStartArray();
            Set<Id> adIds = new Set<Id>();
            if (filter.ShowBooked__c) {
                for (BookedDate__c bd : queryBookedDates()) {
                    g.writeStartObject();
                    g.writeStringField('title', getTitle(bd));
                    g.writeStringField('tooltip', getTooltip(bd));
                    g.writeDateTimeField('start', getStartDateTime(bd.Date__c, bd.Booking__r.Class__r));
                    g.writeDateTimeField('end', getEndDateTime(bd.Date__c, bd.Booking__r.Class__r));
                    g.writeStringField('url', '/' + bd.Booking__r.Id);
                    g.writeStringField('color', '#ff6699');
                    g.writeEndObject();
                    adIds.add(bd.AvailableDate__r.Id);
                }
            }
            if (filter.ShowAvailable__c) {
                for (AvailableDate__c ad : queryAvailableDates(adIds)) {
                    g.writeStartObject();
                    g.writeStringField('title', getTitle(ad));
                    g.writeStringField('tooltip', getTooltip(ad));
                    g.writeDateTimeField('start', getStartDateTime(ad.Date__c, ad.Class__r));
                    g.writeDateTimeField('end', getEndDateTime(ad.Date__c, ad.Class__r));
                    g.writeStringField('url', '/' + ad.Class__r.Id);
                    g.writeStringField('color', '#6699ff');
                    g.writeEndObject();
                }
            }
            g.writeEndArray();
            return g.getAsString();
        }
    }
    
    private String getTitle(BookedDate__c bd) {

        return bd.Booking__r.Name;
    }
    
    private String getTitle(AvailableDate__c ad) {

        return ad.Class__r.Name;
    }
    
    private String getTooltip(BookedDate__c bd) {
    
        Booking__c b = bd.Booking__r;
        Class__c c = b.Class__r;
        
        String s = 'Booking: <b>' + b.Name + '</b>';
        if (b.Client__r != null) {
            s += '<br/>Client: ' + b.Client__r.Name;
        }
        if (b.Client__r != null && b.Client__r.Level__c != null) {
            s += '<br/>Level: ' + b.Client__r.Level__c;
        }
        if (b.Client__r != null && b.Client__r.PreferredHorse__r != null) {
            s += '<br/>Preferred Horse: ' + b.Client__r.PreferredHorse__r.Name;
        }
        
        s += '<br/>';
        
        s += '<br/>Class: <b>' + c.Name + '</b>';
        s += '<br/>Type: ' + c.Type__c;
        if (c.Detail__c != null) {
            s += '<br/>Detail: ' + c.Detail__c;
        }
        if (c.Level__c != null) {
            s += '<br/>Level: ' + c.Level__c;
        }
        if (c.Coach__r != null) {
            s += '<br/>Coach: ' + c.Coach__r.Name;
        }
        
        return s;
    }
    
    private String getTooltip(AvailableDate__c ad) {
    
        Class__c c = ad.Class__r;

        String s = 'Class: <b>' + c.Name + '</b>';
        s += '<br/>Type: ' + c.Type__c;
        if (c.Detail__c != null) {
            s += '<br/>Detail: ' + c.Detail__c;
        }
        if (c.Level__c != null) {
            s += '<br/>Level: ' + c.Level__c;
        }
        if (c.Coach__r != null) {
            s += '<br/>Coach: ' + c.Coach__r.Name;
        }
        
        return s;
    }

    private DateTime getStartDateTime(Date d, Class__c c) {
        return toDateTime(d, defaultTime(c.TimeInMinutes__c));
    }
    
    private DateTime getEndDateTime(Date d, Class__c c) {
        return toDateTime(d, defaultTime(c.TimeInMinutes__c) + defaultLength(c.LengthInMinutes__c));
    }
    
    private DateTime toDateTime(Date d, Integer minutesIntoDay) {
        return DateTime.newInstance(d.year(), d.month(), d.day(), minutesIntoDay / 60, Math.mod(minutesIntoDay, 60), 0);
    }
    
    private Integer defaultTime(Decimal t) {
        return t != null ? t.intValue() : 8;
    }
    
    private Integer defaultLength(Decimal l) {
        return l != null ? l.intValue() : 45;
    }
}