FestinaLenteApp/src/objects/AvailableDate__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Available Dates</relationshipLabel>
        <relationshipName>AvailableDates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DayOfWeekNumber__c</fullName>
        <formula>MOD(Date__c - DATE(2000, 1, 2), 7)</formula>
        <label>Day of Week Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <formula>CASE(DayOfWeekNumber__c, 
    0, &apos;Sunday&apos;, 
    1, &apos;Monday&apos;, 
    2, &apos;Tuesday&apos;, 
    3, &apos;Wednesday&apos;, 
    4, &apos;Thursday&apos;, 
    5, &apos;Friday&apos;, 
    6, &apos;Saturday&apos;, 
    &apos;&apos;
)</formula>
        <label>Day of Week</label>
        <type>Text</type>
    </fields>
    <label>Available Date</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Available Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AvailableDates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/BookedDate__c.object
<CustomObject>
    <fields>
        <fullName>AvailableDate__c</fullName>
        <label>Available Date</label>
        <referenceTo>AvailableDate__c</referenceTo>
        <relationshipLabel>Booked Dates</relationshipLabel>
        <relationshipName>BookedDates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Booked Dates</relationshipLabel>
        <relationshipName>BookedDates</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <formula>AvailableDate__r.Date__c</formula>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <formula>AvailableDate__r.DayOfWeek__c</formula>
        <label>Day of Week</label>
        <type>Text</type>
    </fields>
    <label>Booked Date</label>
    <nameField>
        <displayFormat>BD-{000000}</displayFormat>
        <label>Booked Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booked Dates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Booking__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>AvailableDates__c</fullName>
        <formula>Class__r.AvailableDateCount__c</formula>
        <label>Available Dates</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Class__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>AgeGroup__c</fullName>
        <label>Age Group</label>
        <picklist>
            <picklistValues>
                <fullName>Adult</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Coach__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Coach</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DayOfWeekNumber__c</fullName>
        <formula>CASE(DayOfWeek__c,
    &apos;Sunday&apos;, 0,
    &apos;Monday&apos;, 1,
    &apos;Tuesday&apos;, 2,
    &apos;Wednesday&apos;, 3,
    &apos;Thursday&apos;, 4,
    &apos;Friday&apos;, 5,
    &apos;Saturday&apos;, 6,
    null
)</formula>
        <label>Day of Week Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <label>Day of Week</label>
        <picklist>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Detail__c</fullName>
        <label>Detail</label>
        <picklist>
            <picklistValues>
                <fullName>Lesson</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Stable Management then Lesson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lesson then Stable Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <label>Length</label>
        <picklist>
            <picklistValues>
                <fullName>30 mins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>45 mins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60 mins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90 mins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 hours 30 mins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 hours 30 mins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 hours 30 mins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 hours 30 mins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6 hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6 hours 30 mins</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7 hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7 hours 30 mins</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>B - Beginner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI - Beginner Improver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I - Intermediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SI - Strong Intermediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A - Advanced</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <label>Time</label>
        <picklist>
            <picklistValues>
                <fullName>8 am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:15 am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:30 am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8:45 am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9 am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:15 am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:30 am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9:45 am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10 am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:15 am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:30 am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10:45 am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11 am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:15 am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:30 am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11:45 am</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12 pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:15 pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:30 pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12:45 pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:15 pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:30 pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:45 pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:15 pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:30 pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2:45 pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 pm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3:15 pm</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Adult Camp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EAL Session</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Educational Helpers Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFEP Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pony Camp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Lesson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Private Lesson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Needs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stable Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supported Helpers Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Therapeutic Lesson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training: EAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training: TCP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FestinaLenteApp/src/classes/ClassCopyAll.cls
public class ClassCopyAll {
	
	private enum Week {
		Odd,
		Even,
		Every,
		None
	}
    
    private Set<Id> classIds;
    private List<Date> includedDates;
    
    private List<Class__c> classes;
    private List<Booking__c> bookings;
    private Map<Id, List<Date>> classIdToAvailableDates;
    private Map<Id, List<Date>> bookingIdToBookedDates;
    private Map<Id, Class__c> bookingIdToClass;
    
    public ClassCopyAll(Set<Id> classIds, Set<Date> includedDates) {
    	
        this.classIds = classIds;
        this.includedDates = new List<date>(includedDates);
        this.includedDates.sort();
    }

    public List<Id> copy() {
    	
    	read();
    	return toIds(write());
    }
    
    private List<Id> toIds(List<SObject> sobs) {
    	
    	List<Id> ids = new List<Id>();
    	for (SObject sob : sobs) {
    		ids.add(sob.Id);
    	}
    	return ids;
    }
    
    private List<Class__c> write() {

        // Copy classes
        Map<Id, Id> m = new Map<Id, Id>();
    	List<Class__c> newClasses = classes.deepClone();
    	insert newClasses;
    	for (Integer i = 0; i < classes.size(); i++) {
    		m.put(classes[i].Id, newClasses[i].Id);
    	}

        // Copy bookings
    	List<Booking__c> newBookings = bookings.deepClone();
    	for (Booking__c booking : newBookings) {
    		// Fix parent object reference
    		booking.Class__c = m.get(booking.Class__c);
    	}
    	insert newBookings;
        
        // Group included dates by day
        Map<Integer, List<Date>> dayToDates = new Map<Integer, List<Date>>();
        for (Integer day = 0; day < 7; day++) {
        	dayToDates.put(day, new List<Date>());
        }
    	for (Date d : includedDates) {
    	    dayToDates.get(Dates.dayOfWeek(d)).add(d);
    	}

        // Generate new available dates
        Map<Id, List<AvailableDate__c>> classAds = new Map<Id, List<AvailableDate__c>>();
        List<AvailableDate__c> newAds = new List<AvailableDate__c>();
        for (Integer i = 0; i < newClasses.size(); i++) {
        	Class__c c = newClasses.get(i);
        	
        	List<AvailableDate__c> l = new List<AvailableDate__c>();
        	classAds.put(c.Id, l);
        	
        	// DayOfWeekNumber is a formula field so take from the existing class
        	Decimal dayOfWeekNumber = classes.get(i).DayOfWeekNumber__c;
        	if (dayOfWeekNumber != null) {
        		// Weekly
        		for (Date d : dayToDates.get(dayOfWeekNumber.intValue())) {
        			AvailableDate__c ad = new AvailableDate__c(Class__c = c.Id, Date__c = d);
                    newAds.add(ad);
                    l.add(ad);
        		}
        	} else {
        		// Consecutive days
        		Integer days = classIdToAvailableDates.get(classes.get(i).Id).size();
        		for (Integer j = 0; j < Math.min(days, includedDates.size()); j++) {
        			AvailableDate__c ad = new AvailableDate__c(Class__c = c.Id, Date__c = includedDates.get(j));
                    newAds.add(ad);
                    l.add(ad);
        		}
        	}
        }
        insert newAds;
        
        // Generate new booked dates
        List<BookedDate__c> newBds = new List<BookedDate__c>();
        for (Integer i = 0; i < newBookings.size(); i++) {
        	
        	Booking__c booking = bookings.get(i);
        	Class__c clazz = booking.Class__r;
        	Decimal dayOfWeekNumber = clazz.DayOfWeekNumber__c;
        	if (dayOfWeekNumber != null) {
        		// Weekly
        	
	        	// Get the week pattern from the existing booking
	        	Week w = bestGuessWeeklyPattern(booking);

                // Book according to the pattern
	            Booking__c b = newBookings.get(i);
	        	for (AvailableDate__c ad : classAds.get(b.Class__c)) {
	        		if (book(w, ad.Date__c)) {
	        		    newBds.add(new BookedDate__c(Booking__c = b.Id, AvailableDate__c = ad.Id));
	        		}
	        	}
        	} else {
        		// Consecutive days
        		
        		// See if an existing booking
        		Integer booked = bookingIdToBookedDates.get(booking.Id).size();
        		
        		// If any days booked before, book all this time
        		if (booked > 0) {
	        		Booking__c b = newBookings.get(i);
	                for (AvailableDate__c ad : classAds.get(b.Class__c)) {
	                    newBds.add(new BookedDate__c(Booking__c = b.Id, AvailableDate__c = ad.Id));
	                }
        		}
        	}
        }
        insert newBds;
        
        return newClasses;
    }
    
    private Boolean book(Week w, Date d) {
    	
    	if (w == Week.Every) {
    		return true;
    	} else if (w == Week.None) {
    		return false;
    	}
    	
    	if (Dates.isEvenWeekNumber(d)) {
    		return w == Week.Even;
    	} else {
    		return w == Week.Odd;
    	}
    }
    
    private Week bestGuessWeeklyPattern(Booking__c b) {
    	
    	List<Date> bookedDates = bookingIdToBookedDates.get(b.Id);
    	if (bookedDates.size() == 0) {
    		return Week.None;
    	}
    	
    	Boolean isEven = false;
    	Boolean isOdd = false;
    	for (Date d : bookedDates) {
            if (Dates.isEvenWeekNumber(d)) {
            	isEven = true;
            } else {
            	isOdd = true;
            }
            if (isOdd && isEven) {
            	return Week.Every;
            }
        }

    	if (isEven) {
    		return Week.Even;
    	} else if (isOdd) {
    		return Week.Odd;
    	} else {
    	    return Week.None;
    	}
    }
    
    private void read() {
    	
        classes = [
                select
                        Id,
                        Name,
                        AgeGroup__c,
                        Coach__c,
                        DayOfWeek__c,
                        Detail__c,
                        Length__c,
                        Level__c,
                        Notes__c,
                        Price__c,
                        Time__c,
                        Type__c,
                        DayOfWeekNumber__c,
                        (select Id, Name, Date__c, Class__c from AvailableDates__r order by Date__c),
                        (select Id, Name, Client__c, Class__c, Notes__c, Class__r.DayOfWeekNumber__c from Bookings__r order by Name)
                from Class__c
                where Id in :classIds
                order by Name
                ];
        
        classIdToAvailableDates = new Map<Id, List<Date>>();
        for (Class__c c : classes) {
            classIdToAvailableDates.put(c.Id, new List<Date>());
            for (AvailableDate__c ad : c.AvailableDates__r) {
                classIdToAvailableDates.get(ad.Class__c).add(ad.Date__c);
            }
        }
        
        bookingIdToBookedDates = new Map<Id, List<Date>>();
        bookings = new List<Booking__c>();    
        for (Class__c c : classes) {
            for (Booking__c b : c.Bookings__r) {
                bookings.add(b);
                bookingIdToBookedDates.put(b.Id, new List<Date>());
            }
        }
        for (BookedDate__c bd : [
                select Booking__c, AvailableDate__r.Date__c
                from BookedDate__c
                where Booking__c in :bookingIdToBookedDates.keySet()
                order by AvailableDate__r.Date__c
                ]) {
        	bookingIdToBookedDates.get(bd.Booking__c).add(bd.AvailableDate__r.Date__c);
        }
    }
}