FestinaLenteApp/src/objects/AvailableDate__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Available Dates</relationshipLabel>
        <relationshipName>AvailableDates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DayOfWeekNumber__c</fullName>
        <formula>MOD(Date__c - DATE(2000, 1, 2), 7)</formula>
        <label>Day of Week Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <formula>CASE(DayOfWeekNumber__c, 
    0, &apos;Sunday&apos;, 
    1, &apos;Monday&apos;, 
    2, &apos;Tuesday&apos;, 
    3, &apos;Wednesday&apos;, 
    4, &apos;Thursday&apos;, 
    5, &apos;Friday&apos;, 
    6, &apos;Saturday&apos;, 
    &apos;&apos;
)</formula>
        <label>Day of Week</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WeekNumber__c</fullName>
        <formula>FLOOR((Date__c - DATE(YEAR(Date__c + (MOD(8 - (MOD(Date__c - DATE(1900, 1, 7), 7) + 1), 7) - 3)), 1, 1) + MOD((MOD(DATE(YEAR(Date__c + (MOD(8 - (MOD(Date__c - DATE(1900, 1, 7), 7) + 1) ,7) - 3)), 1, 1) - DATE(1900, 1, 7), 7) + 1) + 1, 7) - 3) / 7 + 1)</formula>
        <label>Week Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Available Date</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Available Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AvailableDates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Class__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>DayOfWeekNumber__c</fullName>
        <formula>CASE(DayOfWeek__c,
    &apos;Sunday&apos;, 0,
    &apos;Monday&apos;, 1,
    &apos;Tuesday&apos;, 2,
    &apos;Wednesday&apos;, 3,
    &apos;Thursday&apos;, 4,
    &apos;Friday&apos;, 5,
    &apos;Saturday&apos;, 6,
    null
)</formula>
        <label>Day of Week Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <label>Day of Week</label>
        <picklist>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FestinaLenteApp/src/classes/AvailableDateTest.cls
@isTest
private class AvailableDateTest {

    private class Fixture {
    
        Class__c clazz;
        AvailableDate__c ad;
        
        Fixture() {
        
            clazz = new Class__c(DayOfWeek__c = 'Friday');
            insert clazz;
  
            // Friday
            ad = new AvailableDate__c(Class__c = clazz.Id, Date__c = Date.newInstance(2013, 1, 11));
            insert ad;
        }
    }
    
    @isTest
    static void formulaFields() {
    
        Fixture f = new Fixture();
        
        AvailableDate__c actual = [
                select DayOfWeek__c, DayOfWeekNumber__c, WeekNumber__c
                from AvailableDate__c
                where Id = :f.ad.Id
                ];
        System.assertEquals('Friday', actual.DayOfWeek__c);
        System.assertEquals(5, actual.DayOfWeekNumber__c);
        System.assertEquals(3, actual.WeekNumber__c);
    }
}