FestinaLenteApp/src/objects/AvailableDate__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Available Date</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Available Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AvailableDates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/classes/SelectableAvailableDate.cls
public class SelectableAvailableDate {

    public SelectableAvailableDate(AvailableDate__c sob, Id bookedDateId) {
        this.sob = sob;
        this.bookedDateId = bookedDateId;
        this.selected = bookedDateId != null;
    }
    
    public AvailableDate__c sob {
        get {
            return sob;
        }
        private set;
    }
    
    public Boolean past {
        get {
            return sob.Date__c < Date.today();
        }
    }
     
    public Id bookedDateId {get; private set;}
    
    public Boolean selected {get; set;}
}