FestinaLenteApp/src/objects/AvailableDate__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Available Dates</relationshipLabel>
        <relationshipName>AvailableDates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DayOfWeekNumber__c</fullName>
        <formula>MOD(Date__c - DATE(2000, 1, 2), 7)</formula>
        <label>Day of Week Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <formula>CASE(DayOfWeekNumber__c, 
    0, &apos;Sunday&apos;, 
    1, &apos;Monday&apos;, 
    2, &apos;Tuesday&apos;, 
    3, &apos;Wednesday&apos;, 
    4, &apos;Thursday&apos;, 
    5, &apos;Friday&apos;, 
    6, &apos;Saturday&apos;, 
    &apos;&apos;
)</formula>
        <label>Day of Week</label>
        <type>Text</type>
    </fields>
    <label>Available Date</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Available Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AvailableDates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Class__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>DayOfWeekNumber__c</fullName>
        <formula>CASE(DayOfWeek__c,
    &apos;Sunday&apos;, 0,
    &apos;Monday&apos;, 1,
    &apos;Tuesday&apos;, 2,
    &apos;Wednesday&apos;, 3,
    &apos;Thursday&apos;, 4,
    &apos;Friday&apos;, 5,
    &apos;Saturday&apos;, 6,
    null
)</formula>
        <label>Day of Week Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <label>Day of Week</label>
        <picklist>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Adult Camp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EAL Session</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Educational Helpers Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFEP Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pony Camp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Lesson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Private Lesson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Needs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stable Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supported Helpers Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Therapeutic Lesson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training: EAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training: TCP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Range__c.object
<CustomObject>
    <description>From/to date range. Not persisted.</description>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <type>Date</type>
    </fields>
    <label>Range</label>
    <nameField>
        <label>Range Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ranges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FestinaLenteApp/src/classes/GenerateAvailableDatesController.cls
public with sharing class GenerateAvailableDatesController {

    private Id classId {
        get {
            if (classId == null) {
                classId = ApexPages.currentPage().getParameters().get('classId');
            }
            return classId;
        }
        private set;
    }

    public Class__c clazz {
        get {
            if (clazz == null) {
                clazz = [
                        select Id, Name, Type__c, DayOfWeek__c, DayOfWeekNumber__c, (select Date__c from AvailableDates__r)
                        from Class__c
                        where Id = :classId
                        ];
            }
            return clazz;
        }
        private set;
    }

    public Range__c range {
        get {
            if (range == null) {
                Date nextMonday = Date.today().addDays(-Dates.dayOfWeek(Date.today()) + 1);
                range = new Range__c(From__c = nextMonday);
            }
            return range;
        }
        private set;
    }

    public PageReference generate() {
    
        // Move start to correct day of week
        Date s = range.From__c;
        while(Dates.dayOfWeek(s) != clazz.DayOfWeekNumber__c) {
           s = s.addDays(1);
        }
        
        Set<Date> alreadyPresentDates = new Set<Date>();
        for (AvailableDate__c ad : clazz.AvailableDates__r) {
            alreadyPresentDates.add(ad.Date__c);
        }
        
        // Add weekly dates
        List<Date> newDates = new List<Date>();
        for (Date d = s; d <= range.To__c; d = d.addDays(7)) {
            if (!alreadyPresentDates.contains(d)) {
                newDates.add(d);
            }
        }
        
        List<AvailableDate__c> inserts = new List<AvailableDate__c>();
        for (Date newDate : newDates) {
            inserts.add(new AvailableDate__c(Class__c = classId, Date__c = newDate));
        }
        insert inserts;
        
        return new PageReference('/' + classId);
    }

    public PageReference cancel() {
        return new PageReference('/' + classId);
    }
}