FestinaLenteApp/src/objects/AvailableDate__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Available Dates</relationshipLabel>
        <relationshipName>AvailableDates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <formula>CASE(DayOfWeekNumber__c, 
    0, &apos;Sunday&apos;, 
    1, &apos;Monday&apos;, 
    2, &apos;Tuesday&apos;, 
    3, &apos;Wednesday&apos;, 
    4, &apos;Thursday&apos;, 
    5, &apos;Friday&apos;, 
    6, &apos;Saturday&apos;, 
    &apos;&apos;
)</formula>
        <label>Day of Week</label>
        <type>Text</type>
    </fields>
    <label>Available Date</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Available Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AvailableDates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/BookedDate__c.object
<CustomObject>
    <fields>
        <fullName>AvailableDate__c</fullName>
        <label>Available Date</label>
        <referenceTo>AvailableDate__c</referenceTo>
        <relationshipLabel>Booked Dates</relationshipLabel>
        <relationshipName>BookedDates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Booked Dates</relationshipLabel>
        <relationshipName>BookedDates</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <formula>HYPERLINK( Booking__r.Client__r.Id ,  Booking__r.Client__r.FirstName + &apos; &apos; +  Booking__r.Client__r.LastName , &quot;_self&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <formula>AvailableDate__r.Date__c</formula>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <formula>AvailableDate__r.DayOfWeek__c</formula>
        <label>Day of Week</label>
        <type>Text</type>
    </fields>
    <label>Booked Date</label>
    <nameField>
        <displayFormat>BD-{000000}</displayFormat>
        <label>Booked Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booked Dates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Booking__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>AvailableDates__c</fullName>
        <formula>Class__r.AvailableDateCount__c</formula>
        <label>Available Dates</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Class__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <label>Day of Week</label>
        <picklist>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FestinaLenteApp/src/classes/ClassCopyAllTest.cls
@isTest
private class ClassCopyAllTest {

    @isTest
    static void basic() {
        
        Contact[] contacts = new Contact[] {
                new Contact(LastName = 'Last1'),
                new Contact(LastName = 'Last2'),
                new Contact(LastName = 'Last3')
                };
        insert contacts;
        
        Class__c weekly = new Class__c(DayOfWeek__c = 'Wednesday');
        Class__c consecutive = new Class__c(DayOfWeek__c = null);
        insert new Class__c[] {weekly, consecutive};
        
        List<AvailableDate__c> ads = new List<AvailableDate__c>();
        ads.add(new AvailableDate__c(Class__c = weekly.Id, Date__c = Date.newInstance(2013, 1, 2)));
        ads.add(new AvailableDate__c(Class__c = weekly.Id, Date__c = Date.newInstance(2013, 1, 9)));
        ads.add(new AvailableDate__c(Class__c = weekly.Id, Date__c = Date.newInstance(2013, 1, 16)));
        ads.add(new AvailableDate__c(Class__c = weekly.Id, Date__c = Date.newInstance(2013, 1, 23)));
        ads.add(new AvailableDate__c(Class__c = consecutive.Id, Date__c = Date.newInstance(2013, 1, 1)));
        ads.add(new AvailableDate__c(Class__c = consecutive.Id, Date__c = Date.newInstance(2013, 1, 2)));
        ads.add(new AvailableDate__c(Class__c = consecutive.Id, Date__c = Date.newInstance(2013, 1, 3)));
        insert ads;
        
        // This will cause a default BookedDate to be created for every AvailableDate
        Booking__c[] bookings = new Booking__c[] {
                new Booking__c(Class__c = weekly.Id, Client__c = contacts[0].Id),
                new Booking__c(Class__c = weekly.Id, Client__c = contacts[1].Id),
                new Booking__c(Class__c = consecutive.Id, Client__c = contacts[2].Id)
                };
        insert bookings;
        
        Set<Id> classIds = new Set<Id>();
        classIds.add(weekly.Id);
        classIds.add(consecutive.Id);
        
        Set<Date> newDates = new Set<Date>();
        for (AvailableDate__c ad : ads) {
            newDates.add(ad.Date__c.addDays(26 * 7));
        }
        
        // Do the copy
        List<Id> newClassIds = new ClassCopyAll(classIds, newDates).copy();
        
        List<Class__c> classesCopy = [
                select
                        DayOfWeek__c,
                        (select Id, Date__c from AvailableDates__r order by Date__c),
                        (select Id from Bookings__r order by Name)
                from Class__c
                where Id in :newClassIds
                order by Name
                ];
        System.assertEquals(2, classesCopy.size());
        
        Class__c weeklyCopy = classesCopy[0];
        System.assertEquals('Wednesday', weeklyCopy.DayOfWeek__c);
        System.assertEquals(4, weeklyCopy.AvailableDates__r.size());
        System.assertEquals(2, weeklyCopy.Bookings__r.size());
        
        Class__c consecutiveCopy = classesCopy[1];
        System.assertEquals(null, consecutiveCopy.DayOfWeek__c);
        System.assertEquals(3, consecutiveCopy.AvailableDates__r.size());
        System.assertEquals(1, consecutiveCopy.Bookings__r.size());
        
        Set<Date> actualDates = new Set<Date>();
        for (Class__c c: classesCopy) {
	        for (AvailableDate__c ad : c.AvailableDates__r) {
	            actualDates.add(ad.Date__c);
	        }
        }
        System.assertEquals(newDates, actualDates);

        BookedDate__c[] bdsCopy = [
                select Id, AvailableDate__r.Date__c
                from BookedDate__c
                where Booking__r.Class__r.Id in :newClassIds
        ];
        System.assertEquals(2 * 4 + 3, bdsCopy.size());
    }
    
    // TODO tests for weekly patterns
}