FestinaLenteApp/src/objects/AvailableDate__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Available Dates</relationshipLabel>
        <relationshipName>AvailableDates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <formula>CASE(DayOfWeekNumber__c, 
    0, &apos;Sunday&apos;, 
    1, &apos;Monday&apos;, 
    2, &apos;Tuesday&apos;, 
    3, &apos;Wednesday&apos;, 
    4, &apos;Thursday&apos;, 
    5, &apos;Friday&apos;, 
    6, &apos;Saturday&apos;, 
    &apos;&apos;
)</formula>
        <label>Day of Week</label>
        <type>Text</type>
    </fields>
    <label>Available Date</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Available Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AvailableDates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Class__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <label>Day of Week</label>
        <picklist>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FestinaLenteApp/src/classes/ClassDeepCloneControllerTest.cls
@isTest
private class ClassDeepCloneControllerTest {

    private class Fixture {

        Class__c clazz;
        AvailableDate__c[] ads;
        
        Fixture() {

            clazz = new Class__c(DayOfWeek__c = 'Monday');
            insert clazz;

            ads = new AvailableDate__c[] {
                    new AvailableDate__c(Class__c = clazz.Id, Date__c = Date.newInstance(2013, 2, 18)),
                    new AvailableDate__c(Class__c = clazz.Id, Date__c = Date.newInstance(2013, 2, 25))
                    };
            insert ads;
        }
    }
    
    @isTest
    static void saveChangeDay() {
        save('Wednesday');
    }
    
    @isTest
    static void saveSameDay() {
        save('Monday');
    }
    
    private static void save(String newDayOfWeek) {
    
        Fixture f = new Fixture();
        
        ClassDeepCloneController c = new ClassDeepCloneController(new ApexPages.StandardController(f.clazz));
        c.clazz.DayOfWeek__c = newDayOfWeek;
        
        // Id follows the slash
        Id newClazzId = (Id) c.save().getUrl().substring(1);
        AvailableDate__c[] actuals = [
                select DayOfWeek__c
                from AvailableDate__c
                where Class__c = :newClazzId
                ];
        System.assertEquals(f.ads.size(), actuals.size());
        for (AvailableDate__c actual : actuals) {
            System.assertEquals(newDayOfWeek, actual.DayOfWeek__c);
        }
    }
    
    @isTest
    static void cancel() {
    
        Fixture f = new Fixture();
        
        ClassDeepCloneController c = new ClassDeepCloneController(new ApexPages.StandardController(f.clazz));
        
        Id cancelId = (Id) c.cancel().getUrl().substring(1);
        System.assertEquals(f.clazz.Id, cancelId);
    }
}