FestinaLenteApp/src/objects/AvailableDate__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Available Dates</relationshipLabel>
        <relationshipName>AvailableDates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Available Date</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Available Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AvailableDates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/BookedDate__c.object
<CustomObject>
    <fields>
        <fullName>AvailableDate__c</fullName>
        <label>Available Date</label>
        <referenceTo>AvailableDate__c</referenceTo>
        <relationshipLabel>Booked Dates</relationshipLabel>
        <relationshipName>BookedDates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Booked Dates</relationshipLabel>
        <relationshipName>BookedDates</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <formula>HYPERLINK( Booking__r.Client__r.Id ,  Booking__r.Client__r.FirstName + &apos; &apos; +  Booking__r.Client__r.LastName , &quot;_self&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client</label>
        <type>Text</type>
    </fields>
    <label>Booked Date</label>
    <nameField>
        <displayFormat>BD-{000000}</displayFormat>
        <label>Booked Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booked Dates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Booking__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>ClassType__c</fullName>
        <formula>TEXT( Class__r.Type__c )</formula>
        <label>Class Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Class__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Waiting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <label>Client</label>
    </recordTypes>
</CustomObject>

FestinaLenteApp/src/classes/BookingAfterTest.cls
@isTest
private class BookingAfterTest {

    private class Fixture {
    
        Class__c clazz;
        Contact contact;
        AvailableDate__c ad;
        Booking__c booking;
        
        Fixture() {
        
            insert clazz = new Class__c();
            insert contact = new Contact(FirstName = 'John', LastName = 'Client', Status__c = 'Waiting', ClassType__c = 'Blah');
            insert ad = new AvailableDate__c(Class__c = clazz.Id);
            
            assertBookedDateCount(0);
            
            insert booking = new Booking__c(Class__c = clazz.Id, Client__c = contact.Id);
            
            assertBookedDateCount(1);
        }
        
        void assertBookedDateCount(Integer expected) {
            System.assertEquals(
                    expected,
                    [select Count() from BookedDate__c where AvailableDate__c = :ad.Id]
                    );
        }
    }
    
    @isTest
    static void test() {

        new Fixture();
    }
}