FestinaLenteApp/src/objects/AvailableDate__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Available Dates</relationshipLabel>
        <relationshipName>AvailableDates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <formula>CASE(DayOfWeekNumber__c, 
    0, &apos;Sunday&apos;, 
    1, &apos;Monday&apos;, 
    2, &apos;Tuesday&apos;, 
    3, &apos;Wednesday&apos;, 
    4, &apos;Thursday&apos;, 
    5, &apos;Friday&apos;, 
    6, &apos;Saturday&apos;, 
    &apos;&apos;
)</formula>
        <label>Day of Week</label>
        <type>Text</type>
    </fields>
    <label>Available Date</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Available Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AvailableDates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/BookedDate__c.object
<CustomObject>
    <fields>
        <fullName>AvailableDate__c</fullName>
        <label>Available Date</label>
        <referenceTo>AvailableDate__c</referenceTo>
        <relationshipLabel>Booked Dates</relationshipLabel>
        <relationshipName>BookedDates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Booked Dates</relationshipLabel>
        <relationshipName>BookedDates</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <formula>HYPERLINK( Booking__r.Client__r.Id ,  Booking__r.Client__r.FirstName + &apos; &apos; +  Booking__r.Client__r.LastName , &quot;_self&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <formula>AvailableDate__r.Date__c</formula>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <formula>AvailableDate__r.DayOfWeek__c</formula>
        <label>Day of Week</label>
        <type>Text</type>
    </fields>
    <label>Booked Date</label>
    <nameField>
        <displayFormat>BD-{000000}</displayFormat>
        <label>Booked Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booked Dates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Booking__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Class__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Coach__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Coach</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>Classes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <label>Day of Week</label>
        <picklist>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Adult Camp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EAL Session</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Educational Helpers Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFEP Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pony Camp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Lesson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Private Lesson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Needs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stable Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supported Helpers Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Therapeutic Lesson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training: EAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training: TCP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ColourCode__c</fullName>
        <label>Colour Code</label>
        <picklist>
            <picklistValues>
                <fullName>AliceBlue (#F0F8FF)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AntiqueWhite (#FAEBD7)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aqua (#00FFFF)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aquamarine (#7FFFD4)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azure (#F0FFFF)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beige (#F5F5DC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bisque (#FFE4C4)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black (#000000)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BlanchedAlmond (#FFEBCD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blue (#0000FF)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BlueViolet (#8A2BE2)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brown (#A52A2A)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BurlyWood (#DEB887)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CadetBlue (#5F9EA0)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chartreuse (#7FFF00)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chocolate (#D2691E)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coral (#FF7F50)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CornflowerBlue (#6495ED)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cornsilk (#FFF8DC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crimson (#DC143C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cyan (#00FFFF)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DarkBlue (#00008B)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DarkCyan (#008B8B)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DarkGoldenRod (#B8860B)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DarkGray (#A9A9A9)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DarkGrey (#A9A9A9)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DarkGreen (#006400)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DarkKhaki (#BDB76B)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DarkMagenta (#8B008B)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DarkOliveGreen (#556B2F)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PreferredHorse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Preferred Horse</label>
        <referenceTo>Horse__c</referenceTo>
        <relationshipLabel>Preferring Clients</relationshipLabel>
        <relationshipName>Clients</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <label>Client</label>
    </recordTypes>
    <recordTypes>
        <fullName>Coach</fullName>
        <active>true</active>
        <label>Coach</label>
    </recordTypes>
</CustomObject>

FestinaLenteApp/src/objects/Horse__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <label>Horse</label>
    <nameField>
        <label>Horse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Horses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FestinaLenteApp/src/classes/PdfControllerTest.cls
@isTest
private class PdfControllerTest {

    private class Fixture {
    
        Horse__c horse;
        Contact coach;
        Class__c clazz;
        Contact client;
        Booking__c booking;
        AvailableDate__c ad;
        BookedDate__c bd;
        
        Fixture(String type, Boolean useClassIdsParameter) {
        
            horse = new Horse__c(
                    Name = 'Paddy'
                    );
            insert horse;
            
            coach = new Contact(
                    FirstName = 'Jane',
                    LastName = 'Coach',
                    ColourCode__c = 'AliceBlue (#F0F8FF)',
                    RecordTypeId = [
                            select Id
                            from RecordType
                            where DeveloperName = 'Coach'
                            and SObjectType = :String.valueOf(Contact.SObjectType)
                            ].Id
                    );
            insert coach;
            
            clazz = new Class__c(
                    Coach__c = coach.Id,
                    DayOfWeek__c = 'Monday',
                    Type__c = type
                    );
            insert clazz;
            
            client = new Contact(
                    FirstName = 'John',
                    LastName = 'Client',
                    PreferredHorse__c = horse.Id,
                    RecordTypeId = [
                            select Id
                            from RecordType
                            where DeveloperName = 'Client'
                            and SObjectType = :String.valueOf(Contact.SObjectType)
                            ].Id
                    );
            insert client;
            
            booking = new Booking__c(
                    Class__c = clazz.Id,
                    Client__c = client.Id
                    );
            insert booking;
            
            ad = new AvailableDate__c(
                    Class__c = clazz.Id,
                    Date__c = Date.newInstance(2013, 2, 18)
                    );
            insert ad;
            
            bd = new BookedDate__c(
                    AvailableDate__c = ad.Id,
                    Booking__c = booking.Id
                    );
            insert bd;

	        Map<String, String> p = ApexPages.currentPage().getParameters();
	        if (useClassIdsParameter) {
	        	p.put('classIds', clazz.Id);
	        } else {
	            p.put('from', '1/1/2013');
	            p.put('to', '6/6/2013');
	            p.put('days', 'Monday');
	            p.put('format', 'PDF');
	            p.put('layout', 'landscape');
	        }
        }
    }
    
    @isTest
    static void termRidings() {

        for (Boolean useClassIdsParameter : new Boolean[] {false, true}) {
        	
	        Fixture f = new Fixture('Term', useClassIdsParameter);
	        
	        PdfController c = new PdfController();
	        List<Table> tables = c.termRidings;
	        System.assertEquals(1, tables.size());
        }
    }
    
    @isTest
    static void privateLessons() {
    
	    for (Boolean useClassIdsParameter : new Boolean[] {false, true}) {
	    	
	        Fixture f = new Fixture('Private Lesson', useClassIdsParameter);
	        
	        PdfController c = new PdfController();
	        List<Table> tables = c.privateLessons;
	        System.assertEquals(1, tables.size());
	    }
    }
    
    @isTest
    static void ponyCamps() {
    
	    for (Boolean useClassIdsParameter : new Boolean[] {false, true}) {
	    	
	        Fixture f = new Fixture('Pony Camp', useClassIdsParameter);
	        
	        PdfController c = new PdfController();
	        List<Table> tables = c.ponyCamps;
	        System.assertEquals(1, tables.size());
	    }
    }
    
    @isTest
    static void termOther() {
    
	    for (Boolean useClassIdsParameter : new Boolean[] {false, true}) {
	    	
	        Fixture f = new Fixture('Term', useClassIdsParameter);
	        
	        PdfController c = new PdfController();
	        System.assertEquals('PDF', c.format);
	        System.assertEquals('landscape', c.layout);
	        System.assertEquals('01/01/2013 - 06/06/2013', c.formattedFromTo);
	    }
    }
}