FestinaLenteApp/src/objects/AvailableDate__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Available Dates</relationshipLabel>
        <relationshipName>AvailableDates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DayOfWeekNumber__c</fullName>
        <formula>MOD(Date__c - DATE(2000, 1, 2), 7)</formula>
        <label>Day of Week Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Available Date</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Available Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AvailableDates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Class__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>DayOfWeekNumber__c</fullName>
        <formula>CASE(DayOfWeek__c,
    &apos;Sunday&apos;, 0,
    &apos;Monday&apos;, 1,
    &apos;Tuesday&apos;, 2,
    &apos;Wednesday&apos;, 3,
    &apos;Thursday&apos;, 4,
    &apos;Friday&apos;, 5,
    &apos;Saturday&apos;, 6,
    null
)</formula>
        <label>Day of Week Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FestinaLenteApp/src/classes/ClassDeepCloneController.cls
public with sharing class ClassDeepCloneController {

    // Public for testing
    public Class__c clazz;

    public ClassDeepCloneController(ApexPages.StandardController controller) {
    
        this.clazz = (Class__c) controller.getRecord();
    }
    
    public AvailableDate__c[] ads {
        get {
            return [
                    select Id, Date__c, DayOfWeekNumber__c
                    from AvailableDate__c
                    where Class__c = :clazz.Id
                    order by Date__c
                    ];
        }
    }
    
    public PageReference save() {
    
        Class__c newClazz = clazz.clone();
        insert newClazz;
        
        // Need to get formula result
        Decimal newClazzDayOfWeekNumber = [
                select DayOfWeekNumber__c
                from Class__c
                where Id = :newClazz.Id
                ].DayOfWeekNumber__c;
        
        // Clone AvailableDates changing date if needed (similar logic in ClassAfterTrigger)      
        List<AvailableDate__c> newAds = new List<AvailableDate__c>();
        for (AvailableDate__c ad : ads) {
            newAds.add(new AvailableDate__c(
                    Class__c = newClazz.Id,
                    Date__c = ad.Date__c.addDays(newClazzDayOfWeekNumber.intValue() - ad.DayOfWeekNumber__c.intValue())
                    ));
        }
        if (newAds.size() > 0) {
            insert newAds;
        }

        return new PageReference('/' + newClazz.Id);
    }
    
    public PageReference cancel() {
        
        return new PageReference('/' + clazz.Id);
    }
}