FestinaLenteApp/src/objects/AvailableDate__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Available Dates</relationshipLabel>
        <relationshipName>AvailableDates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <formula>CASE(DayOfWeekNumber__c, 
    0, &apos;Sunday&apos;, 
    1, &apos;Monday&apos;, 
    2, &apos;Tuesday&apos;, 
    3, &apos;Wednesday&apos;, 
    4, &apos;Thursday&apos;, 
    5, &apos;Friday&apos;, 
    6, &apos;Saturday&apos;, 
    &apos;&apos;
)</formula>
        <label>Day of Week</label>
        <type>Text</type>
    </fields>
    <label>Available Date</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Available Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AvailableDates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Class__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <label>Day of Week</label>
        <picklist>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FestinaLenteApp/src/classes/GenerateAvailableDatesControllerTest.cls
@isTest
private class GenerateAvailableDatesControllerTest {

    private class Fixture {
    
        Class__c clazz;
        AvailableDate__c ad;
        
        Fixture() {
        
            clazz = new Class__c(DayOfWeek__c = 'Friday');
            insert clazz;
            
            // Friday
            ad = new AvailableDate__c(Class__c = clazz.Id, Date__c = Date.newInstance(2013, 1, 18));
            insert ad;
        }
    }

    @isTest
    static void saveAndCancel() {
    
        Fixture f = new Fixture();
        
        ApexPages.currentPage().getParameters().put('classId', f.clazz.Id);
    
        GenerateAvailableDatesController c = new GenerateAvailableDatesController();
        
        // Thursday
        c.range.From__c = Date.newInstance(2013, 1, 10);
        // Saturday
        c.range.To__c = Date.newInstance(2013, 1, 26);
        
        System.assertEquals(f.clazz.Id, c.generate().getUrl().substring(1));
        
        // Fridays
        Date[] expecteds = new Date[] {
                Date.newInstance(2013, 1, 11),
                Date.newInstance(2013, 1, 18),
                Date.newInstance(2013, 1, 25)
                };
        
        List<Date> actuals = new List<Date>();   
        for (AvailableDate__c actual : [
                select Date__c
                from AvailableDate__c
                where Class__c = :f.clazz.Id
                order by Date__c
                ]) {
            actuals.add(actual.Date__c);
        }
        System.assertEquals(expecteds, actuals);
        
        System.assertEquals(f.clazz.Id, c.cancel().getUrl().substring(1));
    }
}