FestinaLenteApp/src/objects/AvailableDate__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Available Dates</relationshipLabel>
        <relationshipName>AvailableDates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <formula>CASE(DayOfWeekNumber__c, 
    0, &apos;Sunday&apos;, 
    1, &apos;Monday&apos;, 
    2, &apos;Tuesday&apos;, 
    3, &apos;Wednesday&apos;, 
    4, &apos;Thursday&apos;, 
    5, &apos;Friday&apos;, 
    6, &apos;Saturday&apos;, 
    &apos;&apos;
)</formula>
        <label>Day of Week</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WeekNumber__c</fullName>
        <formula>FLOOR((Date__c - DATE(YEAR(Date__c + (MOD(8 - (MOD(Date__c - DATE(1900, 1, 7), 7) + 1), 7) - 3)), 1, 1) + MOD((MOD(DATE(YEAR(Date__c + (MOD(8 - (MOD(Date__c - DATE(1900, 1, 7), 7) + 1) ,7) - 3)), 1, 1) - DATE(1900, 1, 7), 7) + 1) + 1, 7) - 3) / 7 + 1)</formula>
        <label>Week Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Available Date</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Available Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AvailableDates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/BookedDate__c.object
<CustomObject>
    <fields>
        <fullName>AvailableDate__c</fullName>
        <label>Available Date</label>
        <referenceTo>AvailableDate__c</referenceTo>
        <relationshipLabel>Booked Dates</relationshipLabel>
        <relationshipName>BookedDates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Booked Dates</relationshipLabel>
        <relationshipName>BookedDates</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <formula>HYPERLINK( Booking__r.Client__r.Id ,  Booking__r.Client__r.FirstName + &apos; &apos; +  Booking__r.Client__r.LastName , &quot;_self&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <formula>AvailableDate__r.Date__c</formula>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <formula>AvailableDate__r.DayOfWeek__c</formula>
        <label>Day of Week</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WeekNumber__c</fullName>
        <formula>AvailableDate__r.WeekNumber__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Week Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Booked Date</label>
    <nameField>
        <displayFormat>BD-{000000}</displayFormat>
        <label>Booked Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booked Dates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Booking__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Class__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <label>Day of Week</label>
        <picklist>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FestinaLenteApp/src/classes/EditBookedDatesController.cls
public with sharing class EditBookedDatesController {

    private Id bookingId {
        get {
            if (bookingId == null) {
                bookingId = ApexPages.currentPage().getParameters().get('bookingId');
            }
            return bookingId;
        }
        private set;
    }
    
    private String retURL {        
        get {
            return ApexPages.currentPage().getParameters().get('retURL');
        }
    }
    
    public Booking__c booking {
        get {
            if (booking == null) {
                booking = [
                        select Id, Name, Client__c, Class__c, Notes__c
                        from Booking__c
                        where Id = :bookingId
                        ];
            }
            return booking;
        }
        private set;
    }
    
    public List<SelectableAvailableDate> availables {
        get {
            if (availables == null) {
            
                Map<Id, Id> bookings = new Map<Id, Id>();
                for (BookedDate__c bd : [
                        select Id, AvailableDate__c
                        from BookedDate__c
                        where Booking__c = :bookingId]) {
                    bookings.put(bd.AvailableDate__c, bd.Id);
                }
                
                availables = new List<SelectableAvailableDate>();
                for (AvailableDate__c ad : [
                        select Id, Name, Date__c, DayOfWeek__c, WeekNumber__c
                        from AvailableDate__c
                        where Class__c in (select Class__c from Booking__c where Id = :bookingId)
                        order by Date__c
                        ]) {
                    availables.add(new SelectableAvailableDate(ad, bookings.get(ad.Id)));
                }
            }
            return availables;
        }
        private set;
    }
    
    public PageReference save() {
    
        // Work out changes needed
        List<BookedDate__c> inserts = new List<BookedDate__c>();
        List<BookedDate__c> deletes = new List<BookedDate__c>();
        for (SelectableAvailableDate available : availables) {
            if (available.selected && available.bookedDateId == null) {
                inserts.add(new BookedDate__c(AvailableDate__c = available.sob.Id, Booking__c = bookingId));
            }
            if (!available.selected && available.bookedDateId != null) {
                deletes.add(new BookedDate__c(Id = available.bookedDateId));
            }
        }
        
        if (inserts.size() > 0) {
            insert inserts;
        }
        if (deletes.size() > 0) {
            delete deletes;
        }
        
        return new PageReference(retURL != null ? retURL : '/' + bookingId);
    }
    
    public PageReference cancel() {
        return new PageReference(retURL != null ? retURL : '/' + bookingId);
    }
}