FestinaLenteApp/src/objects/AvailableDate__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Available Dates</relationshipLabel>
        <relationshipName>AvailableDates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <formula>CASE(DayOfWeekNumber__c, 
    0, &apos;Sunday&apos;, 
    1, &apos;Monday&apos;, 
    2, &apos;Tuesday&apos;, 
    3, &apos;Wednesday&apos;, 
    4, &apos;Thursday&apos;, 
    5, &apos;Friday&apos;, 
    6, &apos;Saturday&apos;, 
    &apos;&apos;
)</formula>
        <label>Day of Week</label>
        <type>Text</type>
    </fields>
    <label>Available Date</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Available Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AvailableDates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Class__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>DayOfWeek__c</fullName>
        <label>Day of Week</label>
        <picklist>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FestinaLenteApp/src/classes/AvailableDateAfterTest.cls
@isTest
private class AvailableDateAfterTest {

    private class Fixture {
    
        Class__c clazz;
        AvailableDate__c ad1;
        AvailableDate__c ad2;

        Fixture(String dayOfWeek) {
            
            clazz = new Class__c(DayOfWeek__c = dayOfWeek);
            insert clazz;
            
            // Monday
            ad1 = new AvailableDate__c(Class__c = clazz.Id, Date__c = Date.newInstance(2013, 2, 18));
            ad2 = new AvailableDate__c(Class__c = clazz.Id, Date__c = Date.newInstance(2013, 2, 25));
            insert new AvailableDate__c[] {ad1, ad2};
        }
    }
    
    @isTest
    static void okChange() {
    
        Fixture f = new Fixture('Monday');
        f.ad1.Date__c = Date.newInstance(2013, 2, 11);
        update f.ad1;
    }
    
    @isTest
    static void wrongDayOfWeekChange() {
    
        Fixture f = new Fixture('Monday');
        f.ad1.Date__c = Date.newInstance(2013, 2, 20);
        try {
            update f.ad1;
            System.assert(false, 'exception expected');
        } catch (Exception e) {
            System.debug('>>> message=' + e.getMessage());
        }
    }
    
    @isTest
    static void dateAlreadyDefinedChange() {
    
        Fixture f = new Fixture('Monday');
        f.ad1.Date__c = f.ad2.Date__c;
        try {
            update f.ad1;
            System.assert(false, 'exception expected');
        } catch (Exception e) {
            System.debug('>>> message=' + e.getMessage());
        }
    }
    
    @isTest
    static void okChangeMutipleDays() {
    
        // No constraint on days when this is set
        Fixture f = new Fixture('Multiple Days');
        f.ad1.Date__c = Date.newInstance(2013, 2, 19);
        update f.ad1;
    }
}