FestinaLenteApp/src/objects/AvailableDate__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Available Dates</relationshipLabel>
        <relationshipName>AvailableDates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WeekNumber__c</fullName>
        <formula>FLOOR((Date__c - DATE(YEAR(Date__c + (MOD(8 - (MOD(Date__c - DATE(1900, 1, 7), 7) + 1), 7) - 3)), 1, 1) + MOD((MOD(DATE(YEAR(Date__c + (MOD(8 - (MOD(Date__c - DATE(1900, 1, 7), 7) + 1) ,7) - 3)), 1, 1) - DATE(1900, 1, 7), 7) + 1) + 1, 7) - 3) / 7 + 1)</formula>
        <label>Week Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Available Date</label>
    <nameField>
        <displayFormat>AD-{000000}</displayFormat>
        <label>Available Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AvailableDates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Class__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FestinaLenteApp/src/classes/DatesTest.cls
@isTest
private class DatesTest {

    @isTest
    static void test() {
    
        System.assertEquals('Monday', Dates.dayIntegerToString(1));
        System.assertEquals(4, Dates.dayStringToInteger('Thursday'));
        System.assertEquals(1, Dates.dayOfWeek(Date.newInstance(2013, 1, 21)));
        
        System.assertEquals(null, Dates.dayIntegerToString(null));
        System.assertEquals(null, Dates.dayStringToInteger(null));
        System.assertEquals(null, Dates.dayOfWeek(null));
    }
    
    @isTest
    static void precedingMonday() {
        
        System.assertEquals(Date.newInstance(2013, 7, 15), Dates.precedingMonday(Date.newInstance(2013, 7, 20)));
        System.assertEquals(Date.newInstance(2013, 7, 15), Dates.precedingMonday(Date.newInstance(2013, 7, 21)));
        
        System.assertEquals(Date.newInstance(2013, 7, 22), Dates.precedingMonday(Date.newInstance(2013, 7, 22)));
        System.assertEquals(Date.newInstance(2013, 7, 22), Dates.precedingMonday(Date.newInstance(2013, 7, 23)));
        System.assertEquals(Date.newInstance(2013, 7, 22), Dates.precedingMonday(Date.newInstance(2013, 7, 24)));
        System.assertEquals(Date.newInstance(2013, 7, 22), Dates.precedingMonday(Date.newInstance(2013, 7, 25)));
        System.assertEquals(Date.newInstance(2013, 7, 22), Dates.precedingMonday(Date.newInstance(2013, 7, 26)));
        System.assertEquals(Date.newInstance(2013, 7, 22), Dates.precedingMonday(Date.newInstance(2013, 7, 27)));
        System.assertEquals(Date.newInstance(2013, 7, 22), Dates.precedingMonday(Date.newInstance(2013, 7, 28)));
        
        System.assertEquals(Date.newInstance(2013, 7, 29), Dates.precedingMonday(Date.newInstance(2013, 7, 29)));
        System.assertEquals(Date.newInstance(2013, 7, 29), Dates.precedingMonday(Date.newInstance(2013, 7, 30)));
        
        System.assertEquals(null, Dates.precedingMonday(null));
    }
    
    @isTest
    static void weekNumber() {
        
        Class__c c = new Class__c();
        insert c;
        
        // Most of this test data taken from http://boards.developerforce.com/t5/Formulas-Validation-Rules/ISO-Week-Calculation/td-p/174749
        Integer[] expecteds = new Integer[] {
                52,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                2,
                2,
                
                37,
                52,
                null,
                
                1,
                1,
                53,
                52,
                1,
                1,
                1
                };
        Date[] ds = new Date[]{};
        for (Date d = Date.newInstance(2012, 12, 30); d < Date.newInstance(2013, 1, 9); d = d.addDays(1)) {
            ds.add(d);
        }
        
        ds.add(Date.newInstance(2013, 9, 13));
        ds.add(Date.newInstance(2013, 12, 25));
        ds.add(null);
        
        ds.add(Date.newInstance(2014, 1, 1));
        ds.add(Date.newInstance(2015, 1, 1));
        ds.add(Date.newInstance(2016, 1, 1));
        ds.add(Date.newInstance(2017, 1, 1));
        ds.add(Date.newInstance(2018, 1, 1));
        ds.add(Date.newInstance(2019, 1, 1));
        ds.add(Date.newInstance(2020, 1, 1));
        
        AvailableDate__c[] ads = new AvailableDate__c[]{};
        for (Date d : ds) {
            ads.add(new AvailableDate__c(Class__c = c.Id, Date__c = d));
        }
        insert ads;
        AvailableDate__c[] actuals = [select WeekNumber__c from AvailableDate__c where Class__c = :c.Id order by Name];
        
        for (Integer i = 0; i < ds.size(); i++) {
            // Check Apex code method
            System.assertEquals(expecteds[i], Dates.weekNumber(ds[i]), 'index=' + i);
            // Check formula field
            System.assertEquals(expecteds[i], actuals[i].WeekNumber__c, 'index=' + i);
        }
    }
    
    @isTest
    static void isEvenWeekNumber() {
    	
    	System.assertEquals(false, Dates.isEvenWeekNumber(Date.newInstance(2014, 1, 1)));
    	System.assertEquals(true, Dates.isEvenWeekNumber(Date.newInstance(2014, 1, 8)));
    	System.assertEquals(null, Dates.isEvenWeekNumber(null));
    }
}