FestinaLenteApp/src/objects/Booking__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LatestBookedDate__c</fullName>
        <label>Latest Booked Date</label>
        <type>Date</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Class__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>InactiveSince__c</fullName>
        <label>Inactive Since</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Waiting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

FestinaLenteApp/src/classes/ContactInactiveSchedulableTest.cls
@isTest
private class ContactInactiveSchedulableTest {

    @isTest
    static void test() {
        
        Contact[] cs = new Contact[] {
                new Contact(FirstName = 'A', LastName = 'Has Recent Booking'),
                new Contact(FirstName = 'B', LastName = 'Has Old Booking'),
                new Contact(FirstName = 'C', LastName = 'Has Recent and Old Booking'),
                new Contact(FirstName = 'D', LastName = 'No Booking')
                };
        insert cs;
        
        Class__c clazz = new Class__c();
        insert clazz;
        
        Booking__c[] bs = new Booking__c[] {
                new Booking__c(Class__c = clazz.Id, Client__c = cs[0].Id, LatestBookedDate__c = Date.today().addYears(-1)),
                new Booking__c(Class__c = clazz.Id, Client__c = cs[1].Id, LatestBookedDate__c = Date.today().addYears(-3)),
                new Booking__c(Class__c = clazz.Id, Client__c = cs[2].Id, LatestBookedDate__c = Date.today().addYears(-1)),
                new Booking__c(Class__c = clazz.Id, Client__c = cs[2].Id, LatestBookedDate__c = Date.today().addYears(-3))
                };
        insert bs;
        
        new ContactInactiveSchedulable().execute(null);
        
        Contact[] actuals = [
                select Status__c, InactiveSince__c
                from Contact
                where Id in :cs
                order by FirstName
                ];
        
        System.assertEquals('Active', actuals[0].Status__c);
        System.assertEquals(null, actuals[0].InactiveSince__c);
        
        System.assertEquals('Inactive', actuals[1].Status__c);
        System.assertEquals(Date.today(), actuals[1].InactiveSince__c);
         
        System.assertEquals('Active', actuals[2].Status__c);
        System.assertEquals(null, actuals[2].InactiveSince__c);
        
        System.assertEquals('Active', actuals[3].Status__c);
        System.assertEquals(null, actuals[3].InactiveSince__c);
    }
}