FestinaLenteApp/src/objects/Booking__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Class__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/TwilioConfiguration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Twilio is used to send SMS messages</description>
    <fields>
        <fullName>AccountSid__c</fullName>
        <label>AccountSid</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AuthToken__c</fullName>
        <label>AuthToken</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FromNumber__c</fullName>
        <label>FromNumber</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Twilio Configuration</label>
</CustomObject>

FestinaLenteApp/src/classes/SmsControllerTest.cls
@isTest
private class SmsControllerTest {

    @isTest
    static void testContact() {
          
        Contact c = new Contact(LastName = 'Doe', MobilePhone = '0861112222');
        insert c;
        
        ApexPages.currentPage().getParameters().put('contactId', c.Id);
        
        doTest();
    }
    
    @isTest
    static void testClass() {
        
        Contact c = new Contact(LastName = 'Doe', MobilePhone = '0861112222');
        insert c;
        
        Class__c clazz = new Class__c();
        insert clazz;
        
        Booking__c b = new Booking__c(Client__c = c.Id, Class__c = clazz.Id);
        insert b;
        
        ApexPages.currentPage().getParameters().put('classId', clazz.Id);
        
        doTest();
    }
    
    private static void doTest() {
        
        TwilioConfiguration__c config = new TwilioConfiguration__c(
                SetupOwnerId = UserInfo.getOrganizationId(),
                AccountSid__c = 'abc',
                AuthToken__c = 'xyz',
                FromNumber__c = '12345678'
                );
        insert config;

        ApexPages.currentPage().getParameters().put('retURL', 'fakeRetURL');
        
        SmsController controller = new SmsController();
        
        System.assertEquals('12345678', controller.fromNumber);
        
        System.assertEquals(1, controller.contacts.size());
        
        SmsController.SelectableContact sc = controller.contacts[0];
        System.assertEquals('+353861112222', sc.cleanMobileNumber);
        
        sc.selected = true;     
        controller.message = 'Message text';
        PageReference send = controller.send();
        System.assertEquals('fakeRetURL', send.getUrl());
        
        PageReference cancel = controller.cancel();
        System.assertEquals('fakeRetURL', cancel.getUrl());
        
        System.assertEquals(null, controller.refreshContacts());
        System.assertEquals(1, controller.contacts.size());
    }
}