FestinaLenteApp/src/objects/Booking__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LatestBookedDate__c</fullName>
        <label>Latest Booked Date</label>
        <type>Date</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>InactiveSince__c</fullName>
        <label>Inactive Since</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Waiting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Client</fullName>
        <active>true</active>
        <label>Client</label>
    </recordTypes>
</CustomObject>

FestinaLenteApp/src/classes/ContactInactiveSchedulable.cls
public with sharing class ContactInactiveSchedulable implements Schedulable {

    public void execute(SchedulableContext context) {
        
        // Contacts that
        // - not already inactive
        // - have had a Booking
        // - but not had one in the last 2 years
        Date d = Date.today().addYears(-2);
        Contact[] contacts = [
                select Id
                from Contact
                where Status__c != 'Inactive'
                and RecordType.Name = 'Client'
                and Id in (select Client__c from Booking__c)
                and Id not in (select Client__c from Booking__c where LatestBookedDate__c > :d)
                ];
        for (Contact c : contacts) {
            c.Status__c = 'Inactive';
            c.InactiveSince__c = Date.today();
        }
        update contacts;
    }
}