FestinaLenteApp/src/objects/Booking__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>ClassType__c</fullName>
        <formula>TEXT( Class__r.Type__c )</formula>
        <label>Class Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Client__c</fullName>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>LatestBookedDate__c</fullName>
        <label>Latest Booked Date</label>
        <type>Date</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{000000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Class__c.object
<CustomObject>
    <customHelpPage>Help</customHelpPage>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Adult Camp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EAL Session</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Educational Helpers Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFEP Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pony Camp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Lesson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Private Lesson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Needs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stable Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supported Helpers Programme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Therapeutic Lesson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training: EAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training: TCP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FestinaLenteApp/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Waiting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

FestinaLenteApp/src/classes/ContactStatusBatchable.cls
/*
 * When bookings move into the past, the status (and active class types) on Contact should change.
 */
public class ContactStatusBatchable implements Database.Batchable<SObject>, Database.Stateful {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        
        // Need to return all Contacts as any may have gone from having bookings to not having bookings
        return Database.getQueryLocator([
		        select Id, Name, Status__c, ClassType__c, ActiveClassType__c, (
		                select Id, Class__r.Type__c
		                from Bookings__r
		                where LatestBookedDate__c != null
		                and LatestBookedDate__c >= TODAY
		                )
		        from Contact
		        order by Name
		        ]);
    }
    
    public void execute(Database.BatchableContext bc, List<SObject> scope) {

        List<Contact> updates = new List<Contact>();
        
        for (SObject sob : scope) {
            Contact c = (Contact) sob;
            
            // Simlar logic in BookingAfter trigger
            
            Set<String> currentActiveClassTypes = c.ActiveClassType__c != null ? new Set<String>(c.ActiveClassType__c.split(';')) : new Set<String>();
            Set<String> currentWaitingClassTypes = c.ClassType__c != null ? new Set<String>(c.ClassType__c.split(';')) : new Set<String>();
            String currentStatus = c.Status__c;
            
            Set<String> newActiveClassTypes = new Set<String>();
            for (Booking__c b : c.Bookings__r) {
                newActiveClassTypes.add(b.Class__r.Type__c);
            }
            
            String newStatus = newActiveClassTypes.size() > 0 ? 'Active' : (currentWaitingClassTypes.size() > 0 ? 'Waiting' : 'Inactive');
            
            if (newStatus != currentStatus || newActiveClassTypes != currentActiveClassTypes) {
                updates.add(new Contact(
                       Id = c.Id,
                       Status__c = newStatus,
                       ActiveClassType__c = Strings.join(newActiveClassTypes, ';')
                       ));
            }
        }
        
        if (updates.size() > 0) {
            update updates;
        }
    }
    
    public void finish(Database.BatchableContext bc) {
    }
}