FestinaLenteApp/src/objects/Printing__c.object
<CustomObject>
    <description>Parameters used to define what to print. Not persisted.</description>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <type>Date</type>
    </fields>
    <label>Printing</label>
    <nameField>
        <displayFormat>P-{000000000}</displayFormat>
        <label>Printing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Printing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FestinaLenteApp/src/classes/PrintingController.cls
public with sharing class PrintingController {

    public Printing__c printing {
        get {
            if (printing == null) {
                // Start on next Monday
                Date defaultFrom = Date.today().addDays(-Dates.dayOfWeek(Date.today()) + 1);
                printing = new Printing__c(From__c = defaultFrom);
            }
            return printing;
        }
        private set;
    }
}